export const authActions = {
  STORE_TOEKN: 'STORE_TOKEN',
  STORE_ISINVALID: 'STORE_ISINVALID',
  STORE_ROLE: 'STORE_ROLE',
  STORE_ACCOUNT_DETAILS: 'STORE_ACCOUNT_DETAILS',
  STORE_JOINT_STATUS: 'STORE_JOINT_STATUS',
};

export const retailerActions = {
  STORE_RETAILER_LIST: 'STORE_RETAILER_LIST',
};

export const attendanceAction = {
  STORE_ATTENDANCE_STATUS: 'STORE_ATTENDANCE_STATUS',
  STORE_ATTENDANCE_LIST: 'STORE_ATTENDANCE_LIST',
  STORE_ATTENDANCE_LOADING: 'STORE_ATTENDANCE_LOADING',
};

export const performanceAction = {
  STORE_TODAYS_ORDER: 'STORE_TODAYS_ORDER',
  STORE_TODAYS_KMS_ORDER: 'STORE_TODAYS_KMS_ORDER',
  STORE_ACHIEVEMENT_AMOUNT: 'STORE_ACHIEVEMENT_AMOUNT',
  STORE_OVERALL_TARGET_AMOUNT: 'STORE_OVERALL_TARGET_AMOUNT',
};

export const orderAction = {
  STORE_CUSTOMER_VISIT_STATUS: 'STORE_CUSTOMER_VISIT_STATUS',
  STOTE_HIDE_CHECKOUT_AFTER_ORDER: 'STOTE_HIDE_CHECKOUT_AFTER_ORDER',
  STORE_CUSTOMER_FOR_ORDER_ON_CALL: 'STORE_CUSTOMER_FOR_ORDER_ON_CALL',
  STORE_CHECK_VISIT_LOADING: 'STORE_CHECK_VISIT_LOADING',
};

export const orderCartActions = {
  STORE_ORDER_CART_ITEMS: 'STORE_ORDER_CART_ITEMS',
  STORE_ORDER_CART_PROMOTIONAL_ITEMS: 'STORE_ORDER_CART_PROMOTIONAL_ITEMS',
  CLEAR_ORDER_CART: 'CLEAR_ORDER_CART',
  CLEAR_ORDER_CART_PROMOTIONAL: 'CLEAR_ORDER_CART_PROMOTIONAL',
};

export const returnCartActions = {
  STORE_RETURN_CART_ITEMS: 'STORE_RETURN_CART_ITEMS',
  STORE_RECENT_VISIT: 'STORE_RECENT_VISIT',
  CLEAR_RETURN_CART: 'CLEAR_RETURN_CART',
  STORE_RETURN_TYPE: 'STORE_RETURN_TYPE',
};
