export const URLS = {
  base: 'http://182.18.155.185/ruchi-soya-nutrition/api/', //test
  //base: 'http://182.18.142.47/ruchi-soya-nutrition/api/', //live

  login: 'users/login',
  profile: 'users/profile',
  errorLog: 'error-logs',
  customer: 'customers/',
  customerVisits: 'customer-visits',
  lastVisits: 'latest-customer-visits',
  orderSummary: 'order-summary',
  topProducts: 'top-products',
  attendanceStatus: 'attendances/punch-status',
  attendancePuchIn: 'attendances/punch-in',
  attendancePunchOut: 'attendances/punch-out',
  attendance: 'attendances/',
  todaysOrder: 'user-performance/today-orders',
  myVisits: 'customers/today',
  routesToday: 'routes/today',
  achievements: 'performances/total-achievements',
  customerClass: 'customer-classes',
  route: 'routes',
  customerType: 'customer-types',
  customerCheckIn: 'customer-visits/check-in',
  customerCheckOut: 'customer-visits/check-out',
  customerVisitStatus: 'customer-visits/status',
  verticals: 'verticals/',
  brands: '/brands/',
  products: '/products',
  predefineFeedback: 'customer-visits/predefined-feedbacks',
  saveFeedback: 'customer-visits/save-feedbacks',
  orders: 'orders/',
  salesReturn: 'sales-returns',
  scheduleSummary: 'customers/schedule-summary/',
  scheduleCustomer: 'customers/scheduled/',
  invoices: 'invoices/',
  geolocations: 'geolocations/',
  salesReturns: 'sales-returns/',
  userHierarchy: 'user-hierarchy/users?id=',
  customerOrderPerformance: 'user-performance/customer-orders',
  topCustomersPerformance: 'user-performance/top-customers',
  topDistributors: 'user-performance/top-distributors',
  todayCustomerOrder: 'user-performance/today-customer-orders',
  topDsms: 'user-performance/top-kams',
  topSalesOfficer: 'user-performance/top-sales-officers',
  dailyOrderPerformance: 'user-performance/daily-orders',
  dailyCustomerOrder: 'user-performance/daily-customer-orders',
  latestOrder: 'orders/latest',
  attendanceSummary: 'user-attendances/today-summary',
  schemes: '/schemes',
  markActive: '/mark-active',
  currentTargets: '/targets/current-brand',
  currentOverAllTargetsAmount: 'targets/current-overall-amount',
  dsms: 'kams',
  salesOfficers: 'sms',
  jointWorkStatus: 'joint-workings/status',
  startJointWork: '/joint-workings/start',
  endJointWork: '/joint-workings/end',
  jointWorkings: '/joint-workings',
  jointVisitCheckedInStatus: '/joint-customer-visits/status',
  jointVisitCheckIn: '/joint-customer-visits/check-in',
  jointVisitCheckOut: '/joint-customer-visits/check-out',
  jointVisitFeedback: '/joint-customer-visits/save-feedback',
  userJointWork: 'user-joint-workings',
  kamDashboard: 'kams/dashboard',
  cumulativeReport: 'user-hierarchy/cumulative-report',
  kamMtd: 'kams/month-till-date',
  kams: 'kams',
  promoterSales: 'promoter-sales',
  promoterClosingStock: 'promoter-closing-stocks',
  allProducts: 'products/all',
  allUsers: 'all-users',
  routeSchedules: 'route-schedules',
  userRouteSchedules: 'user-route-schedules',
};

export const clientId =
  '33OkryzDZsLkqjCaP8_S3IGTGccUcWVBPSQikgGFO2Ir0J_3qWyfh6p99xkkL51IxhnVHlqrljiY8jdmlmHhGvGzCf321yZ4';
export const clientSecret =
  'lrFxI-iSEg8PQEozuUk9fF93mKxpeNfmbopNVxy05mQxN6OMooTAXHhqpe_xxwcinZmYGtXxrbbqnQzZFCKV9agH1yhgUIZzpz6MRxu7yzg=';

export const MapSDKKey = 'c509092e27ffcb2ead37fe1b88a0c2cd';
export const RestAPIkey = '3ec61c9b058136b9cd7c1927682aa80e';
